name: "Deployment"

on:
  push:
   branches: [ "main" ]
  pull_request:
   branches: [ "main" ]      

  workflow_dispatch:

jobs:
  Plan_Dev:
    permissions:   #Permission is required if enabling TFSEC == true
      actions: read
      contents: read
      security-events: write

    uses: Frankoactionstest/githubactionsdemo/.github/workflows/TF_Plan.yml@main
    with:
      path: RG                   ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_vars_file: dev.tfvars    ## Terraform TFVARS (Required)
      az_storage_acc: githubactionsdemo    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: terraformstate
      az_resource_group: TestRG  
      enable_TFSEC: true     
      
      
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      RESOURCE_GROUP: ${{ secrets.DEV_RG }}       


  Deploy_Dev:
    needs: Plan_Dev
    uses: Frankoactionstest/githubactionsdemo/.github/workflows/TF_Apply.yml@main
    with:
      path: RG                  ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_vars_file: dev.tfvars    ## Terraform TFVARS (Required)
      az_storage_acc: githubactionsdemo    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: terraformstate
      az_resource_group: TestRG  
      enable_TFSEC: true             

    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      RESOURCE_GROUP: ${{ secrets.DEV_RG }}       
     

  Plan_Uat:
    uses: Frankoactionstest/githubactionsdemo/.github/workflows/TF_Plan.yml@main
    with:
      path: RG
      tf_vars_file: uat.tfvars
      tf_version: latest
      az_storage_acc: githubactionsdemo    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: terraformstate
      az_resource_group: TestRG  
      enable_TFSEC: true                

    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      RESOURCE_GROUP: ${{ secrets.UAT_RG }}       
       

  Deploy_Uat:
    needs: [ Plan_Uat, Deploy_Dev]
    uses: Frankoactionstest/githubactionsdemo/.github/workflows/TF_Apply.yml@main
    with:
      path: RG
      tf_vars_file: uat.tfvars
      az_storage_acc: githubactionsdemo    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: terraformstate
      az_resource_group: TestRG  
      enable_TFSEC: true         

    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      RESOURCE_GROUP: ${{ secrets.UAT_RG }}       
