name: 'CI using Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    terraform:
      name: 'Terraform'
      runs-on: ubuntu-latest
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
        ARM_CLIENT_SECRET: ${{ secrets.SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
        ARM_TENANT_ID: ${{ secrets.TENANTID }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        
      defaults:
       run:
        shell: bash  
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
           terraform_version: 1.7.5

        - name: Terraform Init
          run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT_NAME" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"   

        - name: Terraform Plan   
          if: github.event_name == 'pull_request'
          run: terraform plan -var-file "./envvariables.tfvars" -out=tfplan 

        - name: Terraform Apply
          if: github.ref == 'refs/heads/main' 
          run: terraform apply "tfplan"